inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "Rakefile"
    - "spec/**/*.rb"
    - "vendor/**/.*"
    - "vendor/**/*"
Layout:
  LineLength: 100
  IndentationStyle:
    IndentationWidth: 2
Metrics/MethodLength:
  Max: 20
